#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LA_Fitness")]
	public partial class LA_FitnessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerOrig_Extended(CustomerOrig_Extended instance);
    partial void UpdateCustomerOrig_Extended(CustomerOrig_Extended instance);
    partial void DeleteCustomerOrig_Extended(CustomerOrig_Extended instance);
    #endregion
		
		public LA_FitnessDataContext() : 
				base(global::DataEntity.Properties.Settings.Default.LA_FitnessConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LA_FitnessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LA_FitnessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LA_FitnessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LA_FitnessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerOrig_Extended> CustomerOrig_Extendeds
		{
			get
			{
				return this.GetTable<CustomerOrig_Extended>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerOrig_Extended")]
	public partial class CustomerOrig_Extended : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private bool _PossessesEmail;
		
		private System.Nullable<bool> _NeedToSignEFT;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<int> _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifiedBy;
		
		private int _MembershipPlan;
		
		private System.Nullable<bool> _EmailAgreement;
		
		private bool _ResponsibleParty;
		
		private System.Nullable<decimal> _PFEnhancementFee;
		
		private System.Nullable<System.DateTime> _EnhancementNextBillDate;
		
		private System.Nullable<int> _CustomerAlertsID;
		
		private string _CampaignSource;
		
		private string _PromoCode;
		
		private System.Nullable<System.DateTime> _FutureDuesChangeDate;
		
		private string _OriginalAgreementNumber;
		
		private string _AnnualAuthPayResponse;
		
		private System.Nullable<System.DateTime> _AnnualAuthPayDate;
		
		private System.Nullable<System.DateTime> _BarcodeFeeWaivedDate;
		
		private System.Nullable<byte> _BypassSignatureCount;
		
		private string _CorporateID;
		
		private string _ProfileImgPath;
		
		private System.Nullable<decimal> _PTAccrualRate;
		
		private System.Nullable<decimal> _PTAccrualTotal;
		
		private System.Data.Linq.Binary _MobileBarcodeSecretKey;
		
		private System.Nullable<int> _EnhancementFeeBillingFrequency;
		
		private System.Nullable<bool> _IsCorporation;
		
		private System.Nullable<int> _PhotoDeletionCount;
		
		private System.Nullable<decimal> _CorporateDuesAmount;
		
		private System.Nullable<bool> _DuesDiscountApplied;
		
		private System.Nullable<bool> _NoCheckInRestriction;
		
		private System.Nullable<System.DateTime> _DigToNonDigitalChangeDate;
		
		private System.Nullable<bool> _HasMobileBarcode;
		
		private System.Nullable<decimal> _FutureDuesAmount;
		
		private System.Nullable<System.DateTime> _EFTUpdateFormDate;
		
		private System.Nullable<byte> _ProductOwed;
		
		private string _LastUsedBarcode;
		
		private System.Nullable<int> _GrossClubNumber;
		
		private System.Nullable<int> _EFTClubNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPossessesEmailChanging(bool value);
    partial void OnPossessesEmailChanged();
    partial void OnNeedToSignEFTChanging(System.Nullable<bool> value);
    partial void OnNeedToSignEFTChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnCreatedByChanging(System.Nullable<int> value);
    partial void OnCreatedByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifiedByChanging(System.Nullable<int> value);
    partial void OnModifiedByChanged();
    partial void OnMembershipPlanChanging(int value);
    partial void OnMembershipPlanChanged();
    partial void OnEmailAgreementChanging(System.Nullable<bool> value);
    partial void OnEmailAgreementChanged();
    partial void OnResponsiblePartyChanging(bool value);
    partial void OnResponsiblePartyChanged();
    partial void OnPFEnhancementFeeChanging(System.Nullable<decimal> value);
    partial void OnPFEnhancementFeeChanged();
    partial void OnEnhancementNextBillDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnhancementNextBillDateChanged();
    partial void OnCustomerAlertsIDChanging(System.Nullable<int> value);
    partial void OnCustomerAlertsIDChanged();
    partial void OnCampaignSourceChanging(string value);
    partial void OnCampaignSourceChanged();
    partial void OnPromoCodeChanging(string value);
    partial void OnPromoCodeChanged();
    partial void OnFutureDuesChangeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFutureDuesChangeDateChanged();
    partial void OnOriginalAgreementNumberChanging(string value);
    partial void OnOriginalAgreementNumberChanged();
    partial void OnAnnualAuthPayResponseChanging(string value);
    partial void OnAnnualAuthPayResponseChanged();
    partial void OnAnnualAuthPayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnnualAuthPayDateChanged();
    partial void OnBarcodeFeeWaivedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBarcodeFeeWaivedDateChanged();
    partial void OnBypassSignatureCountChanging(System.Nullable<byte> value);
    partial void OnBypassSignatureCountChanged();
    partial void OnCorporateIDChanging(string value);
    partial void OnCorporateIDChanged();
    partial void OnProfileImgPathChanging(string value);
    partial void OnProfileImgPathChanged();
    partial void OnPTAccrualRateChanging(System.Nullable<decimal> value);
    partial void OnPTAccrualRateChanged();
    partial void OnPTAccrualTotalChanging(System.Nullable<decimal> value);
    partial void OnPTAccrualTotalChanged();
    partial void OnMobileBarcodeSecretKeyChanging(System.Data.Linq.Binary value);
    partial void OnMobileBarcodeSecretKeyChanged();
    partial void OnEnhancementFeeBillingFrequencyChanging(System.Nullable<int> value);
    partial void OnEnhancementFeeBillingFrequencyChanged();
    partial void OnIsCorporationChanging(System.Nullable<bool> value);
    partial void OnIsCorporationChanged();
    partial void OnPhotoDeletionCountChanging(System.Nullable<int> value);
    partial void OnPhotoDeletionCountChanged();
    partial void OnCorporateDuesAmountChanging(System.Nullable<decimal> value);
    partial void OnCorporateDuesAmountChanged();
    partial void OnDuesDiscountAppliedChanging(System.Nullable<bool> value);
    partial void OnDuesDiscountAppliedChanged();
    partial void OnNoCheckInRestrictionChanging(System.Nullable<bool> value);
    partial void OnNoCheckInRestrictionChanged();
    partial void OnDigToNonDigitalChangeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDigToNonDigitalChangeDateChanged();
    partial void OnHasMobileBarcodeChanging(System.Nullable<bool> value);
    partial void OnHasMobileBarcodeChanged();
    partial void OnFutureDuesAmountChanging(System.Nullable<decimal> value);
    partial void OnFutureDuesAmountChanged();
    partial void OnEFTUpdateFormDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEFTUpdateFormDateChanged();
    partial void OnProductOwedChanging(System.Nullable<byte> value);
    partial void OnProductOwedChanged();
    partial void OnLastUsedBarcodeChanging(string value);
    partial void OnLastUsedBarcodeChanged();
    partial void OnGrossClubNumberChanging(System.Nullable<int> value);
    partial void OnGrossClubNumberChanged();
    partial void OnEFTClubNumberChanging(System.Nullable<int> value);
    partial void OnEFTClubNumberChanged();
    #endregion
		
		public CustomerOrig_Extended()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PossessesEmail", DbType="Bit NOT NULL")]
		public bool PossessesEmail
		{
			get
			{
				return this._PossessesEmail;
			}
			set
			{
				if ((this._PossessesEmail != value))
				{
					this.OnPossessesEmailChanging(value);
					this.SendPropertyChanging();
					this._PossessesEmail = value;
					this.SendPropertyChanged("PossessesEmail");
					this.OnPossessesEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedToSignEFT", DbType="Bit")]
		public System.Nullable<bool> NeedToSignEFT
		{
			get
			{
				return this._NeedToSignEFT;
			}
			set
			{
				if ((this._NeedToSignEFT != value))
				{
					this.OnNeedToSignEFTChanging(value);
					this.SendPropertyChanging();
					this._NeedToSignEFT = value;
					this.SendPropertyChanged("NeedToSignEFT");
					this.OnNeedToSignEFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="Int")]
		public System.Nullable<int> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="Int")]
		public System.Nullable<int> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipPlan", DbType="Int NOT NULL")]
		public int MembershipPlan
		{
			get
			{
				return this._MembershipPlan;
			}
			set
			{
				if ((this._MembershipPlan != value))
				{
					this.OnMembershipPlanChanging(value);
					this.SendPropertyChanging();
					this._MembershipPlan = value;
					this.SendPropertyChanged("MembershipPlan");
					this.OnMembershipPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAgreement", DbType="Bit")]
		public System.Nullable<bool> EmailAgreement
		{
			get
			{
				return this._EmailAgreement;
			}
			set
			{
				if ((this._EmailAgreement != value))
				{
					this.OnEmailAgreementChanging(value);
					this.SendPropertyChanging();
					this._EmailAgreement = value;
					this.SendPropertyChanged("EmailAgreement");
					this.OnEmailAgreementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsibleParty", DbType="Bit NOT NULL")]
		public bool ResponsibleParty
		{
			get
			{
				return this._ResponsibleParty;
			}
			set
			{
				if ((this._ResponsibleParty != value))
				{
					this.OnResponsiblePartyChanging(value);
					this.SendPropertyChanging();
					this._ResponsibleParty = value;
					this.SendPropertyChanged("ResponsibleParty");
					this.OnResponsiblePartyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PFEnhancementFee", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> PFEnhancementFee
		{
			get
			{
				return this._PFEnhancementFee;
			}
			set
			{
				if ((this._PFEnhancementFee != value))
				{
					this.OnPFEnhancementFeeChanging(value);
					this.SendPropertyChanging();
					this._PFEnhancementFee = value;
					this.SendPropertyChanged("PFEnhancementFee");
					this.OnPFEnhancementFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnhancementNextBillDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnhancementNextBillDate
		{
			get
			{
				return this._EnhancementNextBillDate;
			}
			set
			{
				if ((this._EnhancementNextBillDate != value))
				{
					this.OnEnhancementNextBillDateChanging(value);
					this.SendPropertyChanging();
					this._EnhancementNextBillDate = value;
					this.SendPropertyChanged("EnhancementNextBillDate");
					this.OnEnhancementNextBillDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerAlertsID", DbType="Int")]
		public System.Nullable<int> CustomerAlertsID
		{
			get
			{
				return this._CustomerAlertsID;
			}
			set
			{
				if ((this._CustomerAlertsID != value))
				{
					this.OnCustomerAlertsIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerAlertsID = value;
					this.SendPropertyChanged("CustomerAlertsID");
					this.OnCustomerAlertsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampaignSource", DbType="VarChar(50)")]
		public string CampaignSource
		{
			get
			{
				return this._CampaignSource;
			}
			set
			{
				if ((this._CampaignSource != value))
				{
					this.OnCampaignSourceChanging(value);
					this.SendPropertyChanging();
					this._CampaignSource = value;
					this.SendPropertyChanged("CampaignSource");
					this.OnCampaignSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoCode", DbType="VarChar(10)")]
		public string PromoCode
		{
			get
			{
				return this._PromoCode;
			}
			set
			{
				if ((this._PromoCode != value))
				{
					this.OnPromoCodeChanging(value);
					this.SendPropertyChanging();
					this._PromoCode = value;
					this.SendPropertyChanged("PromoCode");
					this.OnPromoCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FutureDuesChangeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FutureDuesChangeDate
		{
			get
			{
				return this._FutureDuesChangeDate;
			}
			set
			{
				if ((this._FutureDuesChangeDate != value))
				{
					this.OnFutureDuesChangeDateChanging(value);
					this.SendPropertyChanging();
					this._FutureDuesChangeDate = value;
					this.SendPropertyChanged("FutureDuesChangeDate");
					this.OnFutureDuesChangeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalAgreementNumber", DbType="VarChar(15)")]
		public string OriginalAgreementNumber
		{
			get
			{
				return this._OriginalAgreementNumber;
			}
			set
			{
				if ((this._OriginalAgreementNumber != value))
				{
					this.OnOriginalAgreementNumberChanging(value);
					this.SendPropertyChanging();
					this._OriginalAgreementNumber = value;
					this.SendPropertyChanged("OriginalAgreementNumber");
					this.OnOriginalAgreementNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnualAuthPayResponse", DbType="NChar(10)")]
		public string AnnualAuthPayResponse
		{
			get
			{
				return this._AnnualAuthPayResponse;
			}
			set
			{
				if ((this._AnnualAuthPayResponse != value))
				{
					this.OnAnnualAuthPayResponseChanging(value);
					this.SendPropertyChanging();
					this._AnnualAuthPayResponse = value;
					this.SendPropertyChanged("AnnualAuthPayResponse");
					this.OnAnnualAuthPayResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnualAuthPayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnnualAuthPayDate
		{
			get
			{
				return this._AnnualAuthPayDate;
			}
			set
			{
				if ((this._AnnualAuthPayDate != value))
				{
					this.OnAnnualAuthPayDateChanging(value);
					this.SendPropertyChanging();
					this._AnnualAuthPayDate = value;
					this.SendPropertyChanged("AnnualAuthPayDate");
					this.OnAnnualAuthPayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarcodeFeeWaivedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BarcodeFeeWaivedDate
		{
			get
			{
				return this._BarcodeFeeWaivedDate;
			}
			set
			{
				if ((this._BarcodeFeeWaivedDate != value))
				{
					this.OnBarcodeFeeWaivedDateChanging(value);
					this.SendPropertyChanging();
					this._BarcodeFeeWaivedDate = value;
					this.SendPropertyChanged("BarcodeFeeWaivedDate");
					this.OnBarcodeFeeWaivedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BypassSignatureCount", DbType="TinyInt")]
		public System.Nullable<byte> BypassSignatureCount
		{
			get
			{
				return this._BypassSignatureCount;
			}
			set
			{
				if ((this._BypassSignatureCount != value))
				{
					this.OnBypassSignatureCountChanging(value);
					this.SendPropertyChanging();
					this._BypassSignatureCount = value;
					this.SendPropertyChanged("BypassSignatureCount");
					this.OnBypassSignatureCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorporateID", DbType="VarChar(25)")]
		public string CorporateID
		{
			get
			{
				return this._CorporateID;
			}
			set
			{
				if ((this._CorporateID != value))
				{
					this.OnCorporateIDChanging(value);
					this.SendPropertyChanging();
					this._CorporateID = value;
					this.SendPropertyChanged("CorporateID");
					this.OnCorporateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileImgPath", DbType="VarChar(1000)")]
		public string ProfileImgPath
		{
			get
			{
				return this._ProfileImgPath;
			}
			set
			{
				if ((this._ProfileImgPath != value))
				{
					this.OnProfileImgPathChanging(value);
					this.SendPropertyChanging();
					this._ProfileImgPath = value;
					this.SendPropertyChanged("ProfileImgPath");
					this.OnProfileImgPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTAccrualRate", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> PTAccrualRate
		{
			get
			{
				return this._PTAccrualRate;
			}
			set
			{
				if ((this._PTAccrualRate != value))
				{
					this.OnPTAccrualRateChanging(value);
					this.SendPropertyChanging();
					this._PTAccrualRate = value;
					this.SendPropertyChanged("PTAccrualRate");
					this.OnPTAccrualRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTAccrualTotal", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> PTAccrualTotal
		{
			get
			{
				return this._PTAccrualTotal;
			}
			set
			{
				if ((this._PTAccrualTotal != value))
				{
					this.OnPTAccrualTotalChanging(value);
					this.SendPropertyChanging();
					this._PTAccrualTotal = value;
					this.SendPropertyChanged("PTAccrualTotal");
					this.OnPTAccrualTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileBarcodeSecretKey", DbType="Binary(10)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary MobileBarcodeSecretKey
		{
			get
			{
				return this._MobileBarcodeSecretKey;
			}
			set
			{
				if ((this._MobileBarcodeSecretKey != value))
				{
					this.OnMobileBarcodeSecretKeyChanging(value);
					this.SendPropertyChanging();
					this._MobileBarcodeSecretKey = value;
					this.SendPropertyChanged("MobileBarcodeSecretKey");
					this.OnMobileBarcodeSecretKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnhancementFeeBillingFrequency", DbType="Int")]
		public System.Nullable<int> EnhancementFeeBillingFrequency
		{
			get
			{
				return this._EnhancementFeeBillingFrequency;
			}
			set
			{
				if ((this._EnhancementFeeBillingFrequency != value))
				{
					this.OnEnhancementFeeBillingFrequencyChanging(value);
					this.SendPropertyChanging();
					this._EnhancementFeeBillingFrequency = value;
					this.SendPropertyChanged("EnhancementFeeBillingFrequency");
					this.OnEnhancementFeeBillingFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCorporation", DbType="Bit")]
		public System.Nullable<bool> IsCorporation
		{
			get
			{
				return this._IsCorporation;
			}
			set
			{
				if ((this._IsCorporation != value))
				{
					this.OnIsCorporationChanging(value);
					this.SendPropertyChanging();
					this._IsCorporation = value;
					this.SendPropertyChanged("IsCorporation");
					this.OnIsCorporationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoDeletionCount", DbType="Int")]
		public System.Nullable<int> PhotoDeletionCount
		{
			get
			{
				return this._PhotoDeletionCount;
			}
			set
			{
				if ((this._PhotoDeletionCount != value))
				{
					this.OnPhotoDeletionCountChanging(value);
					this.SendPropertyChanging();
					this._PhotoDeletionCount = value;
					this.SendPropertyChanged("PhotoDeletionCount");
					this.OnPhotoDeletionCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorporateDuesAmount", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> CorporateDuesAmount
		{
			get
			{
				return this._CorporateDuesAmount;
			}
			set
			{
				if ((this._CorporateDuesAmount != value))
				{
					this.OnCorporateDuesAmountChanging(value);
					this.SendPropertyChanging();
					this._CorporateDuesAmount = value;
					this.SendPropertyChanged("CorporateDuesAmount");
					this.OnCorporateDuesAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuesDiscountApplied", DbType="Bit")]
		public System.Nullable<bool> DuesDiscountApplied
		{
			get
			{
				return this._DuesDiscountApplied;
			}
			set
			{
				if ((this._DuesDiscountApplied != value))
				{
					this.OnDuesDiscountAppliedChanging(value);
					this.SendPropertyChanging();
					this._DuesDiscountApplied = value;
					this.SendPropertyChanged("DuesDiscountApplied");
					this.OnDuesDiscountAppliedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCheckInRestriction", DbType="Bit")]
		public System.Nullable<bool> NoCheckInRestriction
		{
			get
			{
				return this._NoCheckInRestriction;
			}
			set
			{
				if ((this._NoCheckInRestriction != value))
				{
					this.OnNoCheckInRestrictionChanging(value);
					this.SendPropertyChanging();
					this._NoCheckInRestriction = value;
					this.SendPropertyChanged("NoCheckInRestriction");
					this.OnNoCheckInRestrictionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigToNonDigitalChangeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DigToNonDigitalChangeDate
		{
			get
			{
				return this._DigToNonDigitalChangeDate;
			}
			set
			{
				if ((this._DigToNonDigitalChangeDate != value))
				{
					this.OnDigToNonDigitalChangeDateChanging(value);
					this.SendPropertyChanging();
					this._DigToNonDigitalChangeDate = value;
					this.SendPropertyChanged("DigToNonDigitalChangeDate");
					this.OnDigToNonDigitalChangeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasMobileBarcode", DbType="Bit")]
		public System.Nullable<bool> HasMobileBarcode
		{
			get
			{
				return this._HasMobileBarcode;
			}
			set
			{
				if ((this._HasMobileBarcode != value))
				{
					this.OnHasMobileBarcodeChanging(value);
					this.SendPropertyChanging();
					this._HasMobileBarcode = value;
					this.SendPropertyChanged("HasMobileBarcode");
					this.OnHasMobileBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FutureDuesAmount", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> FutureDuesAmount
		{
			get
			{
				return this._FutureDuesAmount;
			}
			set
			{
				if ((this._FutureDuesAmount != value))
				{
					this.OnFutureDuesAmountChanging(value);
					this.SendPropertyChanging();
					this._FutureDuesAmount = value;
					this.SendPropertyChanged("FutureDuesAmount");
					this.OnFutureDuesAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFTUpdateFormDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EFTUpdateFormDate
		{
			get
			{
				return this._EFTUpdateFormDate;
			}
			set
			{
				if ((this._EFTUpdateFormDate != value))
				{
					this.OnEFTUpdateFormDateChanging(value);
					this.SendPropertyChanging();
					this._EFTUpdateFormDate = value;
					this.SendPropertyChanged("EFTUpdateFormDate");
					this.OnEFTUpdateFormDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductOwed", DbType="TinyInt")]
		public System.Nullable<byte> ProductOwed
		{
			get
			{
				return this._ProductOwed;
			}
			set
			{
				if ((this._ProductOwed != value))
				{
					this.OnProductOwedChanging(value);
					this.SendPropertyChanging();
					this._ProductOwed = value;
					this.SendPropertyChanged("ProductOwed");
					this.OnProductOwedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUsedBarcode", DbType="VarChar(11)")]
		public string LastUsedBarcode
		{
			get
			{
				return this._LastUsedBarcode;
			}
			set
			{
				if ((this._LastUsedBarcode != value))
				{
					this.OnLastUsedBarcodeChanging(value);
					this.SendPropertyChanging();
					this._LastUsedBarcode = value;
					this.SendPropertyChanged("LastUsedBarcode");
					this.OnLastUsedBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossClubNumber", DbType="Int")]
		public System.Nullable<int> GrossClubNumber
		{
			get
			{
				return this._GrossClubNumber;
			}
			set
			{
				if ((this._GrossClubNumber != value))
				{
					this.OnGrossClubNumberChanging(value);
					this.SendPropertyChanging();
					this._GrossClubNumber = value;
					this.SendPropertyChanged("GrossClubNumber");
					this.OnGrossClubNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFTClubNumber", DbType="Int")]
		public System.Nullable<int> EFTClubNumber
		{
			get
			{
				return this._EFTClubNumber;
			}
			set
			{
				if ((this._EFTClubNumber != value))
				{
					this.OnEFTClubNumberChanging(value);
					this.SendPropertyChanging();
					this._EFTClubNumber = value;
					this.SendPropertyChanged("EFTClubNumber");
					this.OnEFTClubNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
